macro(MMP_SYSTEM_DEVICE)
	if(CMAKE_SYSTEM_PROCESSOR)
	if(CMAKE_OSX_ARCHITECTURES)
		if("${CMAKE_OSX_ARCHITECTURES}" MATCHES ".*86.*")
			set(MMP_System_Device "X86")
		endif()
		if("${CMAKE_OSX_ARCHITECTURES}" MATCHES "arm64")
			set(MMP_System_Device "ARM64")
		endif()
	elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^aarch64")
		set(MMP_System_Device "ARM64")
	elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^arm64")
		# M1 Mac
		set(MMP_System_Device "ARM64")
	elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^arm")
		set(MMP_System_Device "ARM64")
	elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^amd64" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "^x86_64" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "^AMD64")
		set(MMP_System_Device "X86")
	elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^x86" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "i.86")
		set(MMP_System_Device "X86")
	elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^mips")
		set(MMP_System_Device "MIPS")
	elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^riscv64")
		set(MMP_System_Device "RISCV")
	else()
		message("Unknown CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")
	endif()
	endif()
endmacro()

MMP_SYSTEM_DEVICE()